# Generated by Django 5.1 on 2024-08-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vardas')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pavardė (mamos, tėvo, globėjo)')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Kontaktinis telefonas')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='El. paštas')),
                ('home_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Namų adresas')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Dokumento data')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Priėmimo data')),
                ('child_first_name', models.CharField(max_length=100, verbose_name='Vaiko vardas')),
                ('child_last_name', models.CharField(max_length=100, verbose_name='Vaiko pavardė')),
                ('child_personal_code', models.CharField(max_length=20, verbose_name='Vaiko asmens kodas')),
                ('child_home_address', models.TextField(verbose_name='Namų adresas (faktinė ir deklaruota, jei nesutampa)')),
                ('father_info', models.TextField(verbose_name='Tėtis (vardas, pavardė, kontaktinis telefonas, el. paštas)')),
                ('mother_info', models.TextField(verbose_name='Mama (vardas, pavardė, kontaktinis telefonas, el. paštas)')),
                ('child_health_info', models.TextField(blank=True, null=True, verbose_name='Duomenys apie vaikučio sveikatą')),
                ('child_talents', models.TextField(blank=True, null=True, verbose_name='Vaikučio išskirtiniai gebėjimai, talentai, pomėgiai')),
            ],
        ),
    ]
