# Generated by Django 5.1 on 2024-09-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_registration_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='child_first_last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Vaiko vardas ir pavarde'),
        ),
    ]
