# Generated by Django 5.1 on 2024-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_registration_child_first_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='child_first_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vaiko vardas ir pavarde'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='child_health_info',
            field=models.TextField(null=True, verbose_name='Duomenys apie vaikučio sveikatą'),
        ),
    ]
