# Generated by Django 5.1 on 2024-09-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_alter_registration_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='app/register/word/'),
        ),
    ]
