# Generated by Django 5.1 on 2024-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_registration_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='register/'),
        ),
    ]
