# Generated by Django 5.1 on 2024-09-02 13:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lankymokaina',
            name='additional_info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='lankymokaina',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='nuolaidosirkompensacijos',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
