# Generated by Django 5.1 on 2024-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_lankymokaina_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lankymokaina',
            options={'verbose_name': 'Lankymo kaina', 'verbose_name_plural': 'Lankymo kainos'},
        ),
        migrations.AlterModelOptions(
            name='nuolaidosirkompensacijos',
            options={'verbose_name': 'Nuolaidos is kompensacijos', 'verbose_name_plural': 'Nuolaidos is kompensacijos'},
        ),
    ]
