# Generated by Django 5.1 on 2024-08-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=255)),
                ('about_us_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='activities/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='Grupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupes', to='about_us.aboutuspage')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='about_us.aboutuspage')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('activities', models.ManyToManyField(related_name='routines', to='about_us.activity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='about_us.grupe')),
            ],
            options={
                'unique_together': {('group', 'day')},
            },
        ),
    ]
