# Generated by Django 5.1 on 2024-08-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_alter_dailyroutine_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyroutine',
            name='day',
            field=models.CharField(choices=[('Pirmadienis', 'Pirmadienis'), ('Antradienis', 'Antradienis'), ('Trečiadienis', 'Trečiadienis'), ('Ketvirtadienis', 'Ketvirtadienis'), ('Penktadienis', 'Penktadienis')], max_length=14),
        ),
    ]
