# Generated by Django 5.1 on 2024-08-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_aboutuspage_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuspage',
            name='team_photo',
            field=models.ImageField(blank=True, null=True, upload_to='hero_photos/'),
        ),
    ]
