# Generated by Django 5.1 on 2024-08-31 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_aboutuspage_team_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='icon',
        ),
    ]
