# Generated by Django 5.1 on 2024-09-02 13:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0006_remove_activity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='about_us_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
