# Generated by Django 5.1 on 2024-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0008_aboutuspage_team_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroutine',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
