# Generated by Django 5.1 on 2024-09-09 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0009_alter_dailyroutine_options_dailyroutine_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyroutine',
            options={},
        ),
        migrations.RemoveField(
            model_name='dailyroutine',
            name='order',
        ),
    ]
