# Generated by Django 5.1 on 2024-09-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0011_auto_20240909_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DailyRoutineActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.activity')),
                ('dailyroutine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_us.dailyroutine')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('activity', 'dailyroutine')},
            },
        ),
        migrations.AddField(
            model_name='dailyroutine',
            name='activities',
            field=models.ManyToManyField(related_name='routines', through='about_us.DailyRoutineActivity', to='about_us.activity'),
        ),
    ]
