# Generated by Django 5.1 on 2024-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0012_alter_activity_options_activity_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutuspage',
            options={'verbose_name': 'Apie mus puslapis', 'verbose_name_plural': 'Apie mus puslapiai'},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Užsiėmimas', 'verbose_name_plural': 'Užsiėmimai'},
        ),
        migrations.AlterModelOptions(
            name='dailyroutine',
            options={'verbose_name': 'Rutina', 'verbose_name_plural': 'Rutinos'},
        ),
        migrations.AlterModelOptions(
            name='dailyroutineactivity',
            options={'ordering': ['order'], 'verbose_name': 'Grupių rutinos', 'verbose_name_plural': 'Grupių rutinos'},
        ),
        migrations.AlterModelOptions(
            name='grupe',
            options={'verbose_name': 'Grupė', 'verbose_name_plural': 'Grupės'},
        ),
    ]
