# Generated by Django 5.1 on 2024-08-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_gallerycategory_galleryimage'), ('core', '0003_review'), ('core', '0004_mainpage'), ('core', '0005_feature_hero_mainreview_delete_review_and_more'), ('core', '0006_maingallery_delete_feature'), ('core', '0007_activity_group_teammember_dailyroutine'), ('core', '0008_aboutuspage'), ('core', '0009_group_about_us_page_teammember_about_us_page'), ('core', '0010_alter_group_about_us_page_and_more'), ('core', '0011_rename_group_grupe'), ('core', '0012_rename_group_dailyroutine_grupe_and_more'), ('core', '0013_rename_grupe_dailyroutine_group_and_more'), ('core', '0014_nutrient_weeklynutrition_nutritionpage'), ('core', '0015_alter_weeklynutrition_unique_together_and_more'), ('core', '0016_remove_galleryimage_category_delete_gallerycategory_and_more'), ('core', '0017_remove_hero_main_page_remove_maingallery_main_page_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField(blank=True, max_length=100000)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='activities/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_title', models.CharField(max_length=255)),
                ('about_us_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.aboutuspage')),
            ],
        ),
        migrations.CreateModel(
            name='Grupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('about_us_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupes', to='core.aboutuspage')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('activities', models.ManyToManyField(related_name='routines', to='core.activity')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='core.grupe')),
            ],
            options={
                'unique_together': {('group', 'day')},
            },
        ),
    ]
