# Generated by Django 5.1 on 2024-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255, verbose_name='Hero Title')),
                ('hero_description', models.TextField(verbose_name='Hero Description')),
                ('hero_button_text', models.CharField(max_length=100, verbose_name='Hero Button Text')),
                ('hero_button_url', models.URLField(verbose_name='Hero Button URL')),
            ],
        ),
    ]
