# Generated by Django 5.1 on 2024-08-29 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mainpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('hero_button_text', models.CharField(max_length=50)),
                ('hero_button_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MainReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='hero_button_text',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='hero_button_url',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='hero_description',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='feature',
            name='main_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.mainpage'),
        ),
        migrations.AddField(
            model_name='hero',
            name='main_page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='core.mainpage'),
        ),
        migrations.AddField(
            model_name='mainreview',
            name='main_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.mainpage'),
        ),
    ]
