# Generated by Django 5.1 on 2024-08-29 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feature_hero_mainreview_delete_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_gallery/')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.mainpage')),
            ],
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
