# Generated by Django 5.1 on 2024-08-29 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutuspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='about_us_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.aboutuspage'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='about_us_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.aboutuspage'),
        ),
    ]
