# Generated by Django 5.1 on 2024-08-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_group_about_us_page_teammember_about_us_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.aboutuspage'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='core.aboutuspage'),
        ),
    ]
