# Generated by Django 5.1 on 2024-08-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_group_about_us_page_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Grupe',
        ),
    ]
