# Generated by Django 5.1 on 2024-08-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_group_grupe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='group',
            new_name='grupe',
        ),
        migrations.AlterField(
            model_name='grupe',
            name='about_us_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupes', to='core.aboutuspage'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyroutine',
            unique_together={('grupe', 'day')},
        ),
    ]
