# Generated by Django 5.1 on 2024-08-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_group_dailyroutine_grupe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyroutine',
            old_name='grupe',
            new_name='group',
        ),
        migrations.AlterUniqueTogether(
            name='dailyroutine',
            unique_together={('group', 'day')},
        ),
    ]
