# Generated by Django 5.1 on 2024-08-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_grupe_dailyroutine_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='nutrients/icons/')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('nutrients', models.ManyToManyField(related_name='weekly_nutrition', to='core.nutrient')),
            ],
            options={
                'unique_together': {('day',)},
            },
        ),
        migrations.CreateModel(
            name='NutritionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('week_1', models.ManyToManyField(blank=True, related_name='week_1', to='core.weeklynutrition')),
                ('week_2', models.ManyToManyField(blank=True, related_name='week_2', to='core.weeklynutrition')),
                ('week_3', models.ManyToManyField(blank=True, related_name='week_3', to='core.weeklynutrition')),
                ('week_4', models.ManyToManyField(blank=True, related_name='week_4', to='core.weeklynutrition')),
            ],
        ),
    ]
