# Generated by Django 5.1 on 2024-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_nutrient_weeklynutrition_nutritionpage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklynutrition',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='nutritionpage',
            name='week_1',
        ),
        migrations.RemoveField(
            model_name='nutritionpage',
            name='week_2',
        ),
        migrations.RemoveField(
            model_name='nutritionpage',
            name='week_3',
        ),
        migrations.RemoveField(
            model_name='nutritionpage',
            name='week_4',
        ),
        migrations.AddField(
            model_name='weeklynutrition',
            name='week_number',
            field=models.PositiveIntegerField(choices=[(1, 'Week 1'), (2, 'Week 2'), (3, 'Week 3'), (4, 'Week 4')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='weeklynutrition',
            unique_together={('week_number', 'day')},
        ),
    ]
