# Generated by Django 5.1 on 2024-08-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_weeklynutrition_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='category',
        ),
        migrations.DeleteModel(
            name='GalleryCategory',
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
