# Generated by Django 5.1 on 2024-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Galerijos kategorija', 'verbose_name_plural': 'Galerijos kategorijos'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'verbose_name': 'Galerijos nuotrauka', 'verbose_name_plural': 'Galerijos nuotraukos'},
        ),
    ]
