# Generated by Django 5.1 on 2024-08-31 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_weeklynutrition_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='icon',
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
