# Generated by Django 5.1 on 2024-09-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_remove_nutrient_icon_alter_nutrient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklynutrition',
            name='day',
            field=models.CharField(choices=[('Pirmadienis', 'Pirmadienis'), ('Antradienis', 'Antradienis'), ('Treciadienis', 'Treciadienis'), ('Ketvirtadienis', 'Ketvirtadienis'), ('Penktadienis', 'Penktadienis')], max_length=16),
        ),
    ]
