# Generated by Django 5.1 on 2024-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_weeklynutrition_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklynutrition',
            name='day',
            field=models.CharField(choices=[('Pirmadienis', 'Pirmadienis'), ('Antradienis', 'Antradienis'), ('Trečiadienis', 'Trečiadienis'), ('Ketvirtadienis', 'Ketvirtadienis'), ('Penktadienis', 'Penktadienis')], max_length=16),
        ),
    ]
