# Generated by Django 5.1 on 2024-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_alter_weeklynutrition_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutrient',
            options={'verbose_name': 'Maistas', 'verbose_name_plural': 'Maistai'},
        ),
        migrations.AlterModelOptions(
            name='nutritionpage',
            options={'verbose_name': 'Maisto puslapis', 'verbose_name_plural': 'Maisto puslapiai'},
        ),
        migrations.AlterModelOptions(
            name='weeklynutrition',
            options={'verbose_name': 'Maisto rutina', 'verbose_name_plural': 'Maisto rutinos'},
        ),
    ]
