# Generated by Django 5.1 on 2024-08-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MainGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_gallery/')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='main_page.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=255)),
                ('hero_description', models.TextField()),
                ('hero_button_text', models.CharField(max_length=50)),
                ('hero_button_url', models.URLField()),
                ('main_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='main_page.mainpage')),
            ],
        ),
        migrations.CreateModel(
            name='MainReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_page.mainpage')),
            ],
        ),
    ]
