# Generated by Django 5.1 on 2024-09-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_hero_hero_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Pagrindinis puslapis', 'verbose_name_plural': 'Pagrindiniai puslapiai'},
        ),
    ]
